### PR TITLE
Spark: Add column comment when create clickhouse table

### LINKED ISSUE #174: [feature] add column comment based dataframe scheme when create table
add column comment based dataframe scheme when create table

### PR DESCRIPTION
**Pull request by sketchmind**
close #174

### CODE REVIEW

**Comment by pan3793** [comment]
Thanks, LGTM, would you please make this change in spark-3.3 as well? And better to add a unit test for verification(encouraged but not mandatory)

**Comment by sketchmind** [comment]
> Thanks, LGTM, would you please make this change in spark-3.3 as well? And better to add a unit test for verification(encouraged but not mandatory)

I am now using spark-clickhouse-connector with pyspark, throw java.lang.ClassNotFoundException: xenon.clickhouse.Logging error, which makes me unable to test temporarily

**Comment by sketchmind** [comment]
> Thanks, LGTM, would you please make this change in spark-3.3 as well? And better to add a unit test for verification(encouraged but not mandatory)

ok，I forgot, I will add it right away

**Comment by pan3793** [comment]
> I am now using spark-clickhouse-connector with pyspark, throw java.lang.ClassNotFoundException: xenon.clickhouse.Logging error, which makes me unable to test temporarily

Please use `spark-3.2/clickhouse-spark-runtime/build/libs/clickhouse-spark-runtime-3.2_2.12-0.5.0-SNAPSHOT.jar` for testing.

**Comment by pan3793** [comment]
Please take attention, I just merged https://github.com/housepower/spark-clickhouse-connector/commit/5dbc2fdd923d9685045682b057f5864fd3f19ec5, which changed the build command from `./gradlew build -x test -Dspark_binary_versions=3.2` to `./gradlew build -x test -Dspark_binary_version=3.2`

**Comment by sketchmind** [comment]
> > I am now using spark-clickhouse-connector with pyspark, throw java.lang.ClassNotFoundException: xenon.clickhouse.Logging error, which makes me unable to test temporarily
> 
> Please use `spark-3.2/clickhouse-spark-runtime/build/libs/clickhouse-spark-runtime-3.2_2.12-0.5.0-SNAPSHOT.jar` for testing.


I'm using this file from the beginning, I'll try again

**Review by pan3793 — APPROVED** [review]

**Comment by sketchmind** [comment]
> > LGTM, please click button "Ready for review" when you passed your local testing.
> 
> My pyspark has another problem with jackson during clickhouse initialization. After I test it locally, I will click the ready button

It seems that my JDBC version is too low to report an error

**Comment by pan3793** [comment]
The master branch code depends on the latest clickhouse client, you can choose to use ONE of the following jars

- [clickhouse-jdbc-0.3.2-patch11-all.jar](https://repo1.maven.org/maven2/com/clickhouse/clickhouse-jdbc/0.3.2-patch11/clickhouse-jdbc-0.3.2-patch11-all.jar)
- [clickhouse-jdbc-0.3.2-patch11-grpc.jar](https://repo1.maven.org/maven2/com/clickhouse/clickhouse-jdbc/0.3.2-patch11/clickhouse-jdbc-0.3.2-patch11-grpc.jar)
- [clickhouse-jdbc-0.3.2-patch11-http.jar](https://repo1.maven.org/maven2/com/clickhouse/clickhouse-jdbc/0.3.2-patch11/clickhouse-jdbc-0.3.2-patch11-http.jar)
- [clickhouse-grpc-client-0.3.2-patch11-okhttp.jar](https://repo1.maven.org/maven2/com/clickhouse/clickhouse-grpc-client/0.3.2-patch11/clickhouse-grpc-client-0.3.2-patch11-okhttp.jar)
- [clickhouse-grpc-client-0.3.2-patch11-netty.jar](https://repo1.maven.org/maven2/com/clickhouse/clickhouse-grpc-client/0.3.2-patch11/clickhouse-grpc-client-0.3.2-patch11-netty.jar)
- [clickhouse-grpc-client-0.3.2-patch11-shaded.jar](https://repo1.maven.org/maven2/com/clickhouse/clickhouse-grpc-client/0.3.2-patch11/clickhouse-grpc-client-0.3.2-patch11-shaded.jar)
- [clickhouse-http-client-0.3.2-patch11-shaded.jar](https://repo1.maven.org/maven2/com/clickhouse/clickhouse-http-client/0.3.2-patch11/clickhouse-http-client-0.3.2-patch11-shaded.jar)

**Comment by sketchmind** [comment]
> The master branch code depends on the latest clickhouse client, you can choose to use **one** of the following jars
> 
> * [clickhouse-jdbc-0.3.2-patch11-all.jar](https://repo1.maven.org/maven2/com/clickhouse/clickhouse-jdbc/0.3.2-patch11/clickhouse-jdbc-0.3.2-patch11-all.jar)
> * [clickhouse-jdbc-0.3.2-patch11-grpc.jar](https://repo1.maven.org/maven2/com/clickhouse/clickhouse-jdbc/0.3.2-patch11/clickhouse-jdbc-0.3.2-patch11-grpc.jar)
> * [clickhouse-jdbc-0.3.2-patch11-http.jar](https://repo1.maven.org/maven2/com/clickhouse/clickhouse-jdbc/0.3.2-patch11/clickhouse-jdbc-0.3.2-patch11-http.jar)
> * [clickhouse-grpc-client-0.3.2-patch11-okhttp.jar](https://repo1.maven.org/maven2/com/clickhouse/clickhouse-grpc-client/0.3.2-patch11/clickhouse-grpc-client-0.3.2-patch11-okhttp.jar)
> * [clickhouse-grpc-client-0.3.2-patch11-netty.jar](https://repo1.maven.org/maven2/com/clickhouse/clickhouse-grpc-client/0.3.2-patch11/clickhouse-grpc-client-0.3.2-patch11-netty.jar)
> * [clickhouse-grpc-client-0.3.2-patch11-shaded.jar](https://repo1.maven.org/maven2/com/clickhouse/clickhouse-grpc-client/0.3.2-patch11/clickhouse-grpc-client-0.3.2-patch11-shaded.jar)
> * [clickhouse-http-client-0.3.2-patch11-shaded.jar](https://repo1.maven.org/maven2/com/clickhouse/clickhouse-http-client/0.3.2-patch11/clickhouse-http-client-0.3.2-patch11-shaded.jar)

I don't know why it can't be tested locally, including using scala. I click ready first, you need to do a local test of the feature

**Comment by pan3793** [comment]
OK, let me merge it first and do manual test then.

**Pull request merged**
